### ISSUE TITLE
[META] Checkpoint 2b component set list

### ISSUE THREAD

**Issue by hamilton** [mozilla-ion/ion-core-addon#90]
We're going to wrap [Protocol](https://protocol.mozilla.org/) as Svelte components. Here are the sets of components we'll need:

- [x] some kind of `Layout` component that governs the overall design / breakpoints
- [ ] toolbar for "Current Studies" (#87) view
- [ ] menu element for toolbar
- [x] buttons + variants (implemented in #94)
- [x] three welcome page (#84) cards
- [x] fixed faded footer for the onboarding flow
- [x] whimsy elements for onboarding flow
- [ ] survey elements for demographics view (#86) _(likely to be broken out)_
- [ ] Study card for current studies (#87) _(likely to be broken out)_
- [ ] modal implementation for signing up for a study (#87)
- [ ] notification system (errors, successfuly joined study, etc.)
